### PR TITLE
Pr 1783

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Comment by jppelteret** [comment]
Thanks a lot @tamiko . I'll integrate this into my PR sometime tomorrow!

This looks great, and its nice that one can now drop the template paramater to `inverse_operator` etc. I also like that you decided to split the Trilinos functionality into its own header. As this progressed and the structure got more complex I became undecided about it. But I'm happy that you made that executive decision. The only thing that looks like its missing is a refactoring of `EmptyBlockPayload`. However, thats an easy fix and I'll deal with it.

**Comment by tamiko** [comment]
> The only thing that looks like its missing is a refactoring of
> `EmptyBlockPayload`. However, thats an easy fix and I'll deal with it.

Roger!

Yes, thought about this as well but ran out of time yesterday :-)

Thanks for taking care of it!

**Comment by jppelteret** [comment]
@tamiko I haven't merged these changes yet?! Since you've deleted your branch the "merge" option in GitHub is now commented out. Can I still cherry pick these commits somehow?

**Comment by tamiko** [comment]
@jppelteret Shoot! I accidentally cleaned up too thoroughly.

**Comment by jppelteret** [comment]
Far too thoroughly :-) Thanks a lot for your help and the cleanup. If I hadn't done so already I'll make sure I add you to the changelog entry!

**Pull request merged**
