### PR TITLE
Pr 3931

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Comment by jppelteret** [comment]
Whoops :-)

**Comment by tamiko** [comment]
@jppelteret Do we need it, shall I resurrect the branch?

**Comment by jppelteret** [comment]
Sorry, no not at all. I thought that this was a current branch that you accidentally pushed to my repo. My mistake - its definitely not my day today.

**Comment by tamiko** [comment]
@jppelteret No problem at all. You're not the only confused person around here - I have a very bad habit of deleting branches I still need. That's why I asked.

**Comment by jppelteret** [comment]
@tamiko At least you're sufficiently disciplined to clean up your cruft. This exercise has motivated me to do the same. Thanks! :-)

**Pull request closed without merging**
